### ISSUE TITLE
Implementation for Interface with template not available

### ISSUE THREAD

**Issue by viveknatarajan** [tunnelvisionlabs/InheritanceMargin#18]
If I define an interface for example ICar<T>. I'm unable to see implemented types or interfaces.

**Comment by sharwell** [comment]
Well that's definitely not the expected behavior :frowning: 

:question: What version of Visual Studio are you using (the extension contains 5 different implementations of the same functionality inside the VSIX, so this will help narrow down the one that applies to you)?

:question: Can you provide a complete example/steps to reproduce the problem (e.g. "create file __ with content __, then create file __ with content __, then go to file __ and observe __")?

**Comment by viveknatarajan** [comment]
This was happening with generic interfaces.

Visual Studio Professional 2013 update 3!!!
![margininheritance_1](https://cloud.githubusercontent.com/assets/3109306/12150469/f2f95926-b4cf-11e5-8fd7-33fc2193361c.PNG)

In the attached image, the generic interface(line 8) doesn't show the implemented types. But the non-generic interface (line 16) displays the same.

**Comment by sharwell** [comment]
Ohhhh, I do remember seeing something like that a long time ago. I believe it affect analysis of everything prior to Visual Studio 2015.

The code which locates types that implement an interface in the legacy code base (prior to Visual Studio 2015) is [`SpecializedMatchingMemberCollector.GetDerivedTypes`](https://github.com/tunnelvisionlabs/InheritanceMargin/blob/master/Tvl.VisualStudio.InheritanceMargin.CSharp.Legacy/SpecializedMatchingMemberCollector.cs#L68-L91). I wasn't planning to work in that anymore, but I decided to take a quick look and see what I could find.

I should have a pull request available for you to test shortly.
